### ISSUE TITLE
Botones de donar cargan muy lento.

### ISSUE THREAD

**Issue by fdemian** [UTNianos/issues#10]
Los botones de "donar" en la parte de abajo del banner de UTNianos tardan bastante rato en cargar. Revisar porque esta pasando esto. 

Reportado por @afilgueira .

**Comment by fdemian** [comment]
Relacionado: parece que algunas cosas de ML tardan bastante en cargar... 

![mp_tiempos_sin_cache](https://cloud.githubusercontent.com/assets/1574757/15437140/d82155dc-1e9b-11e6-9df9-5e14e071d9d6.png)

**Comment by afilgueira** [comment]
Arregle los botones. En algun momento deberiamos optimizar el tiempo de carga, ya sea reduciendo lo que cargamos, cacheando o bien haciendo cosas asincronas
